import React from 'react';
import Head from 'next/head';

import { ICard } from '../models/ICard';

import Card from '@/src/components/Card';
import Header from '@/src/components/Header';

import styles from '../styles/CardsPage.module.scss';

interface CardsPageProps {
	cards: ICard[];
}

const CardsPage: React.FC<CardsPageProps> = ({ cards }) => {
	return (
		<>
			<Head>
				<title>AzaliaNow</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="../public/favicon.ico" />
			</Head>
			<Header />
			<main className={styles.main}>
				<ul>
					{cards.map((item) => (
						<Card key={item.id} {...item} />
					))}
				</ul>
			</main>
		</>
	);
};

export default CardsPage;

export async function getServerSideProps() {
	const response = await fetch('https://fakestoreapi.com/products');

	const cards = await response.json();

	return {
		props: {
			cards,
		},
	};
}
